# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K77UoZdLg-C2mphzDM-AoUJSoUyexKCA
"""

import pandas as pd

# Load your dataset
df = pd.read_csv('Crop_recommendation.csv')

# View basic info
print(df.shape)
print(df.columns)
print(df.head())

import matplotlib.pyplot as plt
import seaborn as sns

# Correlation heatmap to see which features relate to crop type
plt.figure(figsize=(10, 6))
# Drop the non-numeric 'label' column before calculating correlation
sns.heatmap(df.drop('label', axis=1).corr(), annot=True, cmap='viridis')
plt.title('Feature Correlation Heatmap')
plt.show()

# Boxplot of rainfall by crop type
plt.figure(figsize=(12, 6))
sns.boxplot(x='label', y='rainfall', data=df)
plt.xticks(rotation=45)
plt.title('Rainfall Distribution per Crop')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

# Split features and labels
X = df.drop('label', axis=1)  # Features (e.g., rainfall, pH, etc.)
y = df['label']               # Target variable (crop type)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

# Set plot size
plt.figure(figsize=(20, 10))

# Plot the decision tree
plot_tree(model, feature_names=X.columns, class_names=model.classes_, filled=True)

plt.title("Crop Prediction Decision Tree")
plt.show()

plt.savefig("crop_tree_visualization.png", dpi=300)

"""The decision tree begins with [feature], indicating it’s the strongest predictor of crop suitability. As we move down the tree, [feature] and [feature] refine the classification further. For example, when [condition], the model predicts [crop], aligning with agricultural best practices in similar environments.

"""

import joblib

# Save the model
joblib.dump(model, "crop_prediction_model.pkl")

# Load it later
loaded_model = joblib.load("crop_prediction_model.pkl")

"""This project applies machine learning to improve crop selection decisions in Kenya, supporting SDG 2 (Zero Hunger). Using rainfall, temperature, soil pH, and nutrient levels, the system predicts optimal crops, helping farmers increase yield and sustainability.

- Data Cleaning & Exploration
- Model Training with Decision Tree
- Visualization of Decision Paths
- Performance Evaluation (accuracy, precision, recall)
- Insight Extraction & Model Export

The model revealed rainfall and potassium levels as the strongest predictors. For regions with high rainfall and balanced pH, crops like rice were recommended, while lower moisture favored maize or millet. This aligns with agricultural practices in semi-arid zones.

"""
